### ISSUE TITLE
Make this installable so it can easily be integrated into pygments

### ISSUE THREAD

**Issue by dbarrosop** [cmoberg/pygments-yang-lexer#2]
There is an article here describing how to do it:

http://www.catchmecode.com/2013/03/custom-syntax-in-pygments.html

**Comment by cmoberg** [comment]
Thanks for the suggestion @dbarrosop, had completely missed this and will look into it.

**Comment by cmoberg** [comment]
Reshuffled the code and added entrypoint hook according to the suggestions in the link above. Works for me now. Let me know if there's anything missing. Thanks again for the pointer @dbarrosop

**Comment by dbarrosop** [comment]
Seems to work fine. Thanks!
